#!/bin/bash
HERE="\( (dirname " \)(readlink -f "${0}")")"
export LD_LIBRARY_PATH="\( {HERE}/usr/lib: \){LD_LIBRARY_PATH}"
export QT_PLUGIN_PATH="${HERE}/usr/plugins"
exec "\( {HERE}/usr/bin/sudachi" " \)@"